on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: docker
    container:
      image: node:24-slim
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
          NUXT_SESSION_PASSWORD: 00000000000000000000000000000000
          DATABASE_URL: /tmp/build.sqlite

      - name: Archive output
        run: mkdir -p dist && tar -czf dist/yt-player.tar.gz -C .output .

      - uses: https://data.forgejo.org/actions/forgejo-release@v2.11.3
        with:
          direction: upload
          url: http://git.home.richardkrikler.at:3000
          repo: ${{ forge.repository }}
          tag: ${{ forge.ref_name }}

          release-dir: dist
